# Generated by Django 4.2.7 on 2025-11-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('financials', 'Financeiro'), ('stock_manager', 'Gerenciador de Inventario'), ('human_resources', 'Recursos Humanos'), ('accountability', 'Contador')], max_length=50),
        ),
    ]
