# Generated by Django 4.2.7 on 2025-11-07 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_membership_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='type',
        ),
    ]
