# Generated by Django 4.2.7 on 2025-11-10 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_verification_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='legal_document',
        ),
        migrations.RemoveField(
            model_name='company',
            name='owner_cnh_document',
        ),
        migrations.RemoveField(
            model_name='company',
            name='proof_of_address_document',
        ),
        migrations.RemoveField(
            model_name='company',
            name='supplemental_documents',
        ),
        migrations.RemoveField(
            model_name='company',
            name='verification_notes',
        ),
    ]
