# Generated by Django 4.2.7 on 2025-11-10 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_remove_company_legal_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='type',
        ),
    ]
