# Generated by Django 4.2.7 on 2025-11-27 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0008_alter_company_cnpj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(help_text='Email do usuário convidado. Usado para buscar usuário existente ou criar novo.', max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('financials', 'Financeiro'), ('stock_manager', 'Gerenciador de Inventario'), ('human_resources', 'Recursos Humanos'), ('accountability', 'Contador')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceito'), ('rejected', 'Recusado'), ('expired', 'Expirado')], default='pending', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='companies.company')),
                ('invited_by', models.ForeignKey(help_text='Admin que enviou o convite.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='Usuário existente convidado. Se None, é um convite para email não cadastrado.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invitation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'status'], name='invitation_email_f2dde1_idx'), models.Index(fields=['user', 'status'], name='invitation_user_id_a5c12a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('company', 'email'), name='unique_pending_invitation_per_company_email'),
        ),
    ]
