# Generated by Django 4.2.7 on 2025-11-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_invitation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='subscription_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_plan',
            field=models.CharField(blank=True, choices=[('monthly', 'Mensal (R$500 via Pix)'), ('quarterly', 'Trimestral (R$1500 via Pix)'), ('semiannual', 'Semestral (R$ 3000 via Pix)'), ('annual', 'Anual (R$6000 via Pix)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
