# Generated by Django 4.2.7 on 2025-11-28 14:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_company_subscription_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(editable=False, max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_centers', to='companies.company')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='companies.costcenter')),
            ],
            options={
                'db_table': 'cost_center',
                'ordering': ['company__name', 'code'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='costcenter',
            unique_together={('company', 'code')},
        ),
    ]
