# Generated by Django 4.2.7 on 2025-12-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_costcenter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='mercadopago_preapproval_plan_id',
            field=models.CharField(blank=True, help_text='ID do plano de assinatura criado no Mercado Pago', max_length=255, null=True, verbose_name='ID do Plano no Mercado Pago'),
        ),
        migrations.AddField(
            model_name='company',
            name='mercadopago_subscription_id',
            field=models.CharField(blank=True, help_text='ID da assinatura ativa no Mercado Pago', max_length=255, null=True, verbose_name='ID da Assinatura no Mercado Pago'),
        ),
    ]
