# Generated by Django 4.2.7 on 2025-12-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_company_mercadopago_preapproval_plan_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='mercadopago_preapproval_plan_id',
        ),
        migrations.AlterField(
            model_name='company',
            name='mercadopago_subscription_id',
            field=models.CharField(blank=True, help_text='ID da assinatura ativa no Mercado Pago (preapproval_id)', max_length=255, null=True, verbose_name='ID da Assinatura no Mercado Pago'),
        ),
        migrations.AlterField(
            model_name='company',
            name='subscription_active',
            field=models.BooleanField(default=False, help_text='Se a empresa tem assinatura ativa (paga ou em trial)', verbose_name='Assinatura Ativa'),
        ),
        migrations.AlterField(
            model_name='company',
            name='subscription_expires_at',
            field=models.DateTimeField(blank=True, help_text='Data de expiração da assinatura atual', null=True, verbose_name='Assinatura expira em'),
        ),
        migrations.AlterField(
            model_name='company',
            name='subscription_plan',
            field=models.CharField(blank=True, help_text='Tipo do plano atual (monthly, quarterly, etc). Veja SubscriptionPlanType em payments.models', max_length=20, null=True, verbose_name='Plano de Assinatura'),
        ),
        migrations.AlterField(
            model_name='company',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, help_text='Data de término do período de teste gratuito', null=True, verbose_name='Trial termina em'),
        ),
    ]
