# Generated by Django 4.2.7 on 2025-12-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_remove_company_mercadopago_preapproval_plan_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='mercadopago_subscription_id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='subscription_plan',
        ),
        migrations.RemoveField(
            model_name='company',
            name='trial_ends_at',
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_started_at',
            field=models.DateTimeField(blank=True, help_text='Data de início da assinatura ativa. Expiração calculada via Subscription.', null=True, verbose_name='Data de Início da Assinatura'),
        ),
        migrations.AlterField(
            model_name='company',
            name='subscription_active',
            field=models.BooleanField(default=False, help_text='Se a empresa tem assinatura ativa (paga ou em trial). Histórico completo em subscriptions.', verbose_name='Assinatura Ativa'),
        ),
        migrations.AlterField(
            model_name='company',
            name='subscription_expires_at',
            field=models.DateTimeField(blank=True, help_text='Data de expiração da assinatura ativa. Calculada como: start_date + duração do plano.', null=True, verbose_name='Assinatura expira em'),
        ),
    ]
