# Generated by Django 4.2.7 on 2025-12-03 17:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0012_company_mercadopago_preapproval_plan_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preapproval_plan_id', models.CharField(help_text='ID retornado pelo Mercado Pago ao criar o plano', max_length=255, unique=True, verbose_name='ID do Plano no Mercado Pago')),
                ('reason', models.CharField(help_text='Descrição que aparece no checkout', max_length=255, verbose_name='Descrição do Plano')),
                ('subscription_plan_type', models.CharField(choices=[('monthly', 'Mensal (R$500 via Pix)'), ('quarterly', 'Trimestral (R$1500 via Pix)'), ('semiannual', 'Semestral (R$ 3000 via Pix)'), ('annual', 'Anual (R$6000 via Pix)')], max_length=20, verbose_name='Tipo de Plano')),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Transação')),
                ('currency_id', models.CharField(default='BRL', max_length=3, verbose_name='Moeda')),
                ('frequency', models.IntegerField(help_text='Quantidade de tempo entre cobranças', verbose_name='Frequência')),
                ('frequency_type', models.CharField(choices=[('days', 'Dias'), ('months', 'Meses')], max_length=20, verbose_name='Tipo de Frequência')),
                ('repetitions', models.IntegerField(blank=True, help_text='Número de cobranças (null = infinito)', null=True, verbose_name='Repetições')),
                ('billing_day', models.IntegerField(help_text='Dia do mês para cobrança (1-28)', verbose_name='Dia de Cobrança')),
                ('free_trial_frequency', models.IntegerField(blank=True, null=True, verbose_name='Duração do Trial')),
                ('free_trial_frequency_type', models.CharField(blank=True, choices=[('days', 'Dias'), ('months', 'Meses')], max_length=20, null=True, verbose_name='Tipo de Duração do Trial')),
                ('init_point', models.URLField(help_text='URL para redirecionar o cliente ao checkout', verbose_name='Link de Checkout')),
                ('back_url', models.URLField(help_text='URL para retornar após checkout', verbose_name='URL de Retorno')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mercadopago_response', models.JSONField(blank=True, default=dict, verbose_name='Resposta do Mercado Pago')),
            ],
            options={
                'verbose_name': 'Plano de Assinatura',
                'verbose_name_plural': 'Planos de Assinatura',
                'db_table': 'subscription_plan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preapproval_id', models.CharField(max_length=255, unique=True, verbose_name='ID da Assinatura no Mercado Pago')),
                ('payer_email', models.EmailField(max_length=254, verbose_name='Email do Pagador')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('authorized', 'Autorizado'), ('paused', 'Pausado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Início')),
                ('next_payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Próxima Data de Pagamento')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Término')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mercadopago_response', models.JSONField(blank=True, default=dict, verbose_name='Resposta do Mercado Pago')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='companies.company', verbose_name='Empresa')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='payments.subscriptionplan', verbose_name='Plano')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
                'db_table': 'subscription',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='subscriptio_company_700c8c_idx'), models.Index(fields=['preapproval_id'], name='subscriptio_preappr_f4d016_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_id', models.CharField(help_text='ID gerado pelo gateway de pagamento', max_length=255, unique=True, verbose_name='ID do Pagamento')),
                ('transaction_id', models.CharField(blank=True, help_text='ID da transação confirmada', max_length=255, null=True, verbose_name='ID da Transação')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('subscription_plan', models.CharField(choices=[('monthly', 'Mensal (R$500 via Pix)'), ('quarterly', 'Trimestral (R$1500 via Pix)'), ('semiannual', 'Semestral (R$ 3000 via Pix)'), ('annual', 'Anual (R$6000 via Pix)')], max_length=20, verbose_name='Plano de Assinatura')),
                ('payment_method', models.CharField(choices=[('pix', 'PIX'), ('credit_card', 'Cartão de Crédito'), ('debit_card', 'Cartão de Débito'), ('bank_slip', 'Boleto Bancário')], default='pix', max_length=20, verbose_name='Método de Pagamento')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Completo'), ('failed', 'Falhou'), ('expired', 'Expirado'), ('refunded', 'Reembolsado')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado em')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Data de expiração do link de pagamento', null=True, verbose_name='Expira em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('pix_code', models.TextField(blank=True, help_text='Copia e cola ou dados do QR Code', null=True, verbose_name='Código PIX')),
                ('gateway_response', models.JSONField(blank=True, default=dict, help_text='Resposta completa do gateway de pagamento', verbose_name='Resposta do Gateway')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='companies.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'db_table': 'payment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='payment_company_a6882c_idx'), models.Index(fields=['payment_id'], name='payment_payment_136d63_idx'), models.Index(fields=['created_at'], name='payment_created_6be7be_idx')],
            },
        ),
    ]
