# Generated by Django 4.2.7 on 2025-12-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='subscription_plan',
            field=models.CharField(choices=[('monthly', 'Mensal'), ('quarterly', 'Trimestral'), ('semiannual', 'Semestral'), ('annual', 'Anual')], max_length=20, verbose_name='Plano de Assinatura'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='subscription_plan_type',
            field=models.CharField(choices=[('monthly', 'Mensal'), ('quarterly', 'Trimestral'), ('semiannual', 'Semestral'), ('annual', 'Anual')], max_length=20, verbose_name='Tipo de Plano'),
        ),
    ]
