# Generated by Django 4.2.7 on 2025-12-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_subscription_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='billing_day',
            field=models.IntegerField(blank=True, help_text='Dia fixo do mês para cobrança (1-28). Se None, cobra no dia da primeira compra', null=True, verbose_name='Dia de Cobrança'),
        ),
    ]
