# Generated by Django 4.2.7 on 2025-12-04 16:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_external_reference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='external_reference',
        ),
        migrations.AddField(
            model_name='payment',
            name='code',
            field=models.CharField(default=uuid.uuid4, help_text='Código único gerado automaticamente para o pagamento', max_length=255, unique=True, verbose_name='Código Único do Pagamento'),
        ),
    ]
