# Generated by Django 4.2.7 on 2025-12-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_remove_payment_external_reference_payment_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='external_reference',
            field=models.CharField(blank=True, help_text='Código usado para identificar o pagamento no webhook (ex: company_id)', max_length=255, null=True, verbose_name='Código de Referência Externa'),
        ),
    ]
