# Generated by Django 4.2.7 on 2025-12-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_payment_external_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='external_reference',
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_trial',
            field=models.BooleanField(default=False, help_text='Se esta assinatura é um período de trial gratuito (14 dias)', verbose_name='É Trial'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Data de início da assinatura. Expiração = start_date + duração do plano', null=True, verbose_name='Data de Início'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['company', 'is_trial'], name='subscriptio_company_338fcf_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('is_trial', True), models.Q(('status', 'authorized'), ('status', 'pending'), _connector='OR')), fields=('company',), name='unique_active_trial_per_company'),
        ),
    ]
