# Generated by Django 4.2.7 on 2025-12-04 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_remove_payment_external_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(blank=True, help_text='Assinatura à qual este pagamento pertence (para pagamentos recorrentes)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.subscription', verbose_name='Assinatura'),
        ),
    ]
