# Generated by Django 4.2.7 on 2024-05-20

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_active_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trial_ends_at',
            field=models.DateTimeField(default=apps.users.models.default_trial_end),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_plan',
            field=models.CharField(blank=True, choices=[('monthly', 'Mensal (R$500 via Pix)'), ('quarterly', 'Trimestral (R$1500 via Pix)'), ('semiannual', 'Semestral (R$500/mês via Pix)'), ('annual', 'Anual (R$500/mês via Pix)')], max_length=20, null=True),
        ),
    ]
