# Generated by Django 4.2.7 on 2025-11-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_subscription_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active_company',
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription_plan',
            field=models.CharField(blank=True, choices=[('monthly', 'Mensal (R$500 via Pix)'), ('quarterly', 'Trimestral (R$1500 via Pix)'), ('semiannual', 'Semestral (R$ 3000 via Pix)'), ('annual', 'Anual (R$6000 via Pix)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
