# Generated by Django 4.2.7 on 2025-11-27 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_must_change_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscription_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_expires_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_plan',
        ),
    ]
