# Generated by Django 4.2.7 on 2025-11-27 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_user_subscription_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='trial_ends_at',
        ),
    ]
