# Generated by Django 4.2.7 on 2025-12-02 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_costcenter_and_more'),
        ('users', '0010_remove_user_trial_ends_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='operator_company',
            field=models.ForeignKey(blank=True, help_text='Empresa à qual o operador pertence (apenas para usuários OPERADOR)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operators', to='companies.company'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('plataforma', 'Usuário da Plataforma'), ('operador', 'Usuário Operador')], default='plataforma', help_text='Tipo de usuário: PLATAFORMA (com login) ou OPERADOR (apenas histórico)', max_length=20),
        ),
    ]
