# Generated by Django 4.2.7 on 2025-11-10 16:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        # Remove as tabelas antigas e recria com UUID
        migrations.RunSQL(
            sql="""
                -- Remove foreign keys e tabelas
                DROP TABLE IF EXISTS inventory_movements CASCADE;
                DROP TABLE IF EXISTS stock_item CASCADE;
                DROP TABLE IF EXISTS products CASCADE;
                DROP TABLE IF EXISTS product_category CASCADE;
                DROP TABLE IF EXISTS inventory CASCADE;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        
        # Recria Inventory com UUID
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='companies.company')),
            ],
            options={
                'verbose_name_plural': 'Inventories',
                'db_table': 'inventory',
                'ordering': ['company', 'name'],
            },
        ),
        
        # Recria ProductCategory com UUID
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='companies.company')),
            ],
            options={
                'db_table': 'product_category',
                'ordering': ['company', 'name'],
                'unique_together': {('company', 'name')},
            },
        ),
        
        # Recria Product com UUID
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('min_stock_level', models.BigIntegerField(default=0)),
                ('default_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='companies.company')),
                ('product_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.productcategory')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['company', 'name'],
                'unique_together': {('company', 'name')},
            },
        ),
        
        # Recria StockItem com UUID
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_on_hand', models.BigIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='companies.company')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='inventory.inventory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='inventory.product')),
            ],
            options={
                'db_table': 'stock_item',
                'ordering': ['company', 'product', 'inventory'],
                'unique_together': {('company', 'product', 'inventory')},
            },
        ),
        
        # Recria InventoryMovement com UUID
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_changed', models.BigIntegerField()),
                ('type', models.CharField(choices=[('in_purchase', 'Entrada - Compra'), ('in_adjustment', 'Entrada - Ajuste'), ('in_transfer', 'Entrada - Transferência'), ('out_sale', 'Saída - Venda'), ('out_adjustment', 'Saída - Ajuste'), ('out_transfer', 'Saída - Transferência'), ('out_loss', 'Saída - Perda')], max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='companies.company')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.stockitem')),
            ],
            options={
                'db_table': 'inventory_movements',
                'ordering': ['-created_at'],
            },
        ),
    ]
