# Generated by Django 4.2.7 on 2025-12-01 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_id_alter_inventorymovement_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='related_inventory',
            field=models.ForeignKey(blank=True, help_text='Inventário de destino (para OUT_TRANSFER) ou origem (para IN_TRANSFER)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_movements', to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='transfer_reference',
            field=models.UUIDField(blank=True, help_text='UUID que vincula os dois movimentos (saída e entrada) da mesma transferência', null=True),
        ),
    ]
