# Generated by Django 4.2.7 on 2025-12-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventorymovement_related_inventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='min_stock_level',
            field=models.BigIntegerField(default=0, help_text='Estoque mínimo específico para este produto neste inventário'),
        ),
    ]
