# Generated by Django 4.2.7 on 2025-11-10 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0006_remove_company_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('conta_corrente', 'Conta Corrente'), ('conta_poupanca', 'Conta Poupança'), ('banco_de_creditos', 'Banco de Créditos'), ('carteira_digital', 'Carteira Digital'), ('cofre', 'Cofre')], max_length=25)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='companies.company')),
            ],
            options={
                'db_table': 'bank_account',
                'ordering': ['company__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_registers', to='companies.company')),
                ('default_bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_registers', to='financials.bankaccount')),
            ],
            options={
                'db_table': 'cash_register',
                'ordering': ['company__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='companies.company')),
            ],
            options={
                'db_table': 'category',
                'ordering': ['company__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('type', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa'), ('transferencia_interna', 'Transferência Interna'), ('transferencia_externa', 'Transferência Externa')], max_length=25)),
                ('transaction_date', models.DateField()),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='financials.bankaccount')),
                ('cash_register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='financials.cashregister')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='financials.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='companies.company')),
                ('linked_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverse_linked_transaction', to='financials.transaction')),
            ],
            options={
                'db_table': 'transaction',
                'ordering': ['-transaction_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RecurringIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('frequency', models.CharField(choices=[('daily', 'Diário'), ('weekly', 'Semanal'), ('monthly', 'Mensal'), ('quarterly', 'Trimestral'), ('yearly', 'Anual')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('next_due_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_incomes', to='financials.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_incomes', to='companies.company')),
            ],
            options={
                'db_table': 'recurring_income',
                'ordering': ['company__name', 'next_due_date'],
            },
        ),
        migrations.CreateModel(
            name='RecurringBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('frequency', models.CharField(choices=[('daily', 'Diário'), ('weekly', 'Semanal'), ('monthly', 'Mensal'), ('quarterly', 'Trimestral'), ('yearly', 'Anual')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('next_due_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_bills', to='financials.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_bills', to='companies.company')),
            ],
            options={
                'db_table': 'recurring_bill',
                'ordering': ['company__name', 'next_due_date'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('recebido', 'Recebido')], default='pendente', max_length=20)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='financials.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='companies.company')),
                ('payment_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_payment', to='financials.transaction')),
            ],
            options={
                'db_table': 'income',
                'ordering': ['-due_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('a_vencer', 'A Vencer'), ('quitada', 'Quitada')], default='a_vencer', max_length=20)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='financials.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='companies.company')),
                ('payment_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_payment', to='financials.transaction')),
            ],
            options={
                'db_table': 'bill',
                'ordering': ['-due_date', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('company', 'name', 'type'), name='uniq_category_company_name_type'),
        ),
        migrations.AddConstraint(
            model_name='cashregister',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_cash_register_company_name'),
        ),
    ]
