# Generated by Django 4.2.7 on 2025-11-10 15:34

from django.db import migrations, models


def initialize_balances(apps, schema_editor):
    BankAccount = apps.get_model('financials', 'BankAccount')
    for account in BankAccount.objects.all():
        BankAccount.objects.filter(pk=account.pk).update(current_balance=account.initial_balance)


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.RunPython(initialize_balances, migrations.RunPython.noop),
    ]
