# Generated by Django 4.2.7 on 2025-11-24 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0003_bank_contact_and_category_hierarchy'),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, reverse_code=migrations.RunPython.noop),
    ]
