# Generated by Django 4.2.7 on 2025-11-24 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0004_seed_banks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='bank',
            name='logo',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to='bank_logos/',
                validators=[django.core.validators.FileExtensionValidator(['svg'])],
            ),
        ),
    ]
