# Generated by Django 4.2.7 on 2025-11-24 15:40

from django.db import migrations, models, transaction


def populate_category_codes(apps, schema_editor):
    Category = apps.get_model('financials', 'Category')

    def assign_children(parent):
        children = list(
            Category.objects.filter(parent=parent).order_by('created_at', 'id')
        )
        for idx, child in enumerate(children, start=1):
            child.code = f'{parent.code}.{idx}'
            child.save(update_fields=['code'])
            assign_children(child)

    with transaction.atomic():
        for company_id in (
            Category.objects.order_by().values_list('company_id', flat=True).distinct()
        ):
            roots = list(
                Category.objects.filter(company_id=company_id, parent__isnull=True)
                .order_by('created_at', 'id')
            )
            for idx, root in enumerate(roots, start=1):
                root.code = str(idx)
                root.save(update_fields=['code'])
                assign_children(root)


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0005_bank_logo_filefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_category_company_code'),
        ),
        migrations.RunPython(populate_category_codes, reverse_code=migrations.RunPython.noop),
    ]
