# Generated by Django 4.2.7 on 2025-11-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0007_transaction_refund_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='type',
            field=models.CharField(choices=[('conta_corrente', 'Conta Corrente'), ('conta_poupanca', 'Conta Poupança'), ('banco_de_creditos', 'Banco de Créditos'), ('caixinha_banco', 'Caixinha do Banco')], max_length=25),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa'), ('transferencia_interna', 'Transferência Interna'), ('transferencia_externa', 'Transferência Externa'), ('estorno', 'Estorno / Devolução')], max_length=25),
        ),
    ]
