# Generated by Django 4.2.7 on 2025-11-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0008_bankaccount_description_alter_bankaccount_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
    ]
