# Generated by Django 4.2.7 on 2025-11-28 21:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_costcenter_and_more'),
        ('financials', '0013_order_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringIncomeReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField()),
                ('received_on', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('recebido', 'Recebido')], default='pendente', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_income_receipts', to='companies.company')),
                ('recurring_income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='financials.recurringincome')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_income_receipts', to='financials.transaction')),
            ],
            options={
                'db_table': 'recurring_income_receipt',
                'ordering': ['-due_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RecurringBillPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField()),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('quitada', 'Quitada')], default='pendente', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_bill_payments', to='companies.company')),
                ('recurring_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='financials.recurringbill')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_bill_payments', to='financials.transaction')),
            ],
            options={
                'db_table': 'recurring_bill_payment',
                'ordering': ['-due_date', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='recurringincomereceipt',
            constraint=models.UniqueConstraint(fields=('company', 'recurring_income', 'due_date'), name='uniq_recurring_income_receipt_cycle'),
        ),
        migrations.AddConstraint(
            model_name='recurringbillpayment',
            constraint=models.UniqueConstraint(fields=('company', 'recurring_bill', 'due_date'), name='uniq_recurring_bill_payment_cycle'),
        ),
    ]
