# Generated by Django 4.2.7 on 2025-12-03 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('financials', '0014_recurringincomereceipt_recurringbillpayment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringbill',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_bills', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='recurringincome',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_incomes', to='contacts.contact'),
        ),
    ]
