# Generated by Django 4.2.7 on 2025-12-04 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0015_add_contact_to_recurring'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recurringbillpayment',
            name='uniq_recurring_bill_payment_cycle',
        ),
        migrations.RemoveConstraint(
            model_name='recurringincomereceipt',
            name='uniq_recurring_income_receipt_cycle',
        ),
        migrations.AlterField(
            model_name='recurringbillpayment',
            name='recurring_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='financials.recurringbill'),
        ),
        migrations.AlterField(
            model_name='recurringincomereceipt',
            name='recurring_income',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='financials.recurringincome'),
        ),
        migrations.AddConstraint(
            model_name='recurringbillpayment',
            constraint=models.UniqueConstraint(condition=models.Q(('recurring_bill__isnull', False)), fields=('company', 'recurring_bill', 'due_date'), name='uniq_recurring_bill_payment_cycle'),
        ),
        migrations.AddConstraint(
            model_name='recurringincomereceipt',
            constraint=models.UniqueConstraint(condition=models.Q(('recurring_income__isnull', False)), fields=('company', 'recurring_income', 'due_date'), name='uniq_recurring_income_receipt_cycle'),
        ),
    ]
